name: Iconictakeover
favicon: null
layout_spectrum: 0.62968
typography_spectrum: 0.77473
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Iconictakeover
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefff9'
    - '#c7632f'
    - '#d0d1cb'
    - '#5b3824'
    - '#6e6f69'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
