name: Iconictakeover
favicon: null
layout_spectrum: 0.8929174
typography_spectrum: 0.2445194
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Iconic Source
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#180000'
    - '#98895B'
    - '#655439'
    - '#FF0000'
    - '#B3AC9B'
  brandStrength: 0.4325464
  lightness: 0.6028668
  saturation: 0.5016863
  rhythmicContrast: 0.5615515
purpose: []
